language: python
sudo: false
python:
  - "2.7"
before_install:
  # nothing to do, currently
# command to install dependencies
install:
  - pip install zope.interface
  - python setup.py dev
# command to run tests
script:
  - py.test
